# 1. Info

Notebook with all the code needed to solve the homework for the first week of the machine learning zoomcamp.

## Install the required libraries

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Getting the data

For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-14 13:36:20--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: 'housing.csv.1'

housing.csv.1       100%[===================>]   1.36M  8.55MB/s    in 0.2s    

2023-09-14 13:36:21 (8.55 MB/s) - 'housing.csv.1' saved [1423529/1423529]



In [4]:
data = pd.read_csv('housing.csv')

# 2. Coding

## Question 1

What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [5]:
pd.__version__

'1.4.4'

## Question 2
How many columns are in the dataset?

* 10
* 6560
* 10989
* 20640

In [6]:
len(data.columns)

10

## Question 3
Which columns in the dataset have missing values?

* total_rooms
* total_bedrooms
* both of the above
* no empty columns in the dataset

In [7]:
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4
How many unique values does the ocean_proximity column have?

* 3
* 5
* 7
* 9

In [8]:
data['ocean_proximity'].nunique()

5

## Question 5
What's the average value of the median_house_value for the houses located near the bay?

* 49433
* 124805
* 259212
* 380440

In [9]:
int(data.query("ocean_proximity == 'NEAR BAY'")['median_house_value'].mean())

259212

## Question 6

1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

Has it changed?

Hint: take into account only 3 digits after the decimal point.

* Yes
* No

In [10]:
round(data['total_bedrooms'].mean(),3)

537.871

In [11]:
data.fillna(round(data['total_bedrooms'].mean(),3), inplace=True)

In [12]:
data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [13]:
round(data['total_bedrooms'].mean(),3)

537.871

## Question 7

1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

* -1.4812
* 0.001
* 5.6992
* 23.1233

In [14]:
data_islands = data.query("ocean_proximity == 'ISLAND'")

In [15]:
data_filtered = data_islands[['housing_median_age','total_rooms','total_bedrooms']].copy()

In [16]:
X =  data_filtered.values

In [17]:
XT = X.transpose()
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [18]:
XTX = XT.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [19]:
XTX_invs = np.linalg.inv(XTX)
XTX_invs

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [20]:
y = np.array([950,1300,800,1000,1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [21]:
w = XTX_invs.dot(X.T).dot(y)

In [22]:
round(w[-1],4)

5.6992

# End of the notebook